services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Asia/Seoul

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"

  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false  # 보안 인증 비활성화
      - xpack.security.http.ssl.enabled=false  # HTTPS 비활성화 (HTTP 사용)
      - xpack.security.transport.ssl.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
#      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_HOST}
#      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PORT}
    ports:
      - "${ELASTICSEARCH_PORT}:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "${KIBANA_PORT}:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:${ELASTICSEARCH_PORT}

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
      - ./logstash/mysql-connector-java-8.0.26:/usr/share/logstash/config/mysql-connector-java-8.0.26
    ports:
      - "${LOGSTASH_PORT}:5044"
    depends_on:
      - mysql
      - elasticsearch
    environment:
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - ELASTICSEARCH_PORT=${ELASTICSEARCH_PORT}