input {
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/config/mysql-connector-java-8.0.26/mysql-connector-java-8.0.26.jar"
    jdbc_driver_class => "com.mysql.cj.jdbc.Driver"
    jdbc_connection_string => "jdbc:mysql://mysql:${MYSQL_PORT}/${MYSQL_DATABASE}"
    jdbc_user => "${MYSQL_USERNAME}"
    jdbc_password => "${MYSQL_PASSWORD}"
    schedule => "*/5 * * * *"
    statement => "SELECT id, name, address, max_table_count, remaining_table_count, category, is_deleted, updated_at, UNIX_TIMESTAMP(updated_at) AS unix_ts_in_secs FROM restaurant WHERE (UNIX_TIMESTAMP(updated_at) > :sql_last_value AND updated_at < NOW()) ORDER BY updated_at ASC"
    use_column_value => true
    tracking_column => "unix_ts_in_secs"
    tracking_column_type => "numeric"
  }
}
filter {
  mutate {
    remove_field => ["@version","unix_ts_in_secs","updated_at"]
  }
}
output {
  elasticsearch {
    hosts => ["http://elasticsearch:${ELASTICSEARCH_PORT}"]
    index => "restaurants"
    document_id => "%{id}"
  }
  stdout { codec => json_lines }
}
